[package]
name = "rust"
version = "0.1.0"
authors = ["Karl 'NaN' Wikström <karl@wikstrom.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
scan_fmt = "0.2.5"